/* Ejecutar con el servidor activo: npm test. No modifica archivos de la app. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const BASE = process.env.POCKETSTORE_URL || 'http://localhost:8000/';
const evidence = process.env.POCKETSTORE_EVIDENCE === '1';
(async () => {
  const browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? {executablePath: process.env.CHROME_PATH} : {}) });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(BASE);
    await page.waitForFunction(() => document.querySelectorAll('.card').length === 10 && navigator.serviceWorker.controller && !document.querySelector('#refresh').disabled);
    await page.waitForFunction(() => !document.querySelector('#refresh').textContent.includes('Actualizando'));
    assert.match(await page.locator('#offline-ready').innerText(), /Ya puedes desconectarte/);
    assert.equal(await page.locator('.card').count(), 10);
    const source = await page.locator('#source').innerText();
    console.log('Carga inicial:', source);
    if (evidence) await page.screenshot({ path: path.join(ROOT, 'docs/images/01-catalogo.png'), fullPage: true });
    await page.locator('#search').fill('gwenborough');
    assert.equal(await page.locator('.card').count(), 1);
    assert.equal(await page.locator('.card h3').innerText(), 'Leanne Graham');
    await page.locator('#search').fill('sin coincidencias xyz');
    assert(await page.locator('#empty').isVisible());
    await page.locator('#search').fill('');
    await page.getByRole('button', { name: 'Añadir a favoritos a Leanne Graham', exact: true }).click();
    await page.locator('#favorites').click();
    assert.equal(await page.locator('.card').count(), 1);
    await page.getByRole('button', { name: 'Ver ficha de Leanne Graham', exact: true }).click();
    assert(await page.locator('#details').isVisible());
    assert.match(await page.locator('#detail-content').innerText(), /Sincere@april.biz/);
    if (evidence) await page.screenshot({path: path.join(ROOT, 'docs/images/02-ficha.png')});
    await page.keyboard.press('Escape');
    assert.equal(await page.evaluate(() => document.activeElement.textContent), 'Ver ficha ↗');
    await page.locator('#all').click();
    await context.setOffline(true);
    await page.reload();
    await page.waitForFunction(() => document.querySelectorAll('.card').length === 10 && !document.querySelector('#refresh').textContent.includes('Actualizando'));
    assert.equal(await page.locator('#connection').innerText(), 'Sin conexión');
    assert(await page.locator('#refresh').isDisabled());
    assert.equal(await page.locator('#favorite-count').innerText(), '1');
    if (source.includes('actualizados')) assert.match(await page.locator('#source').innerText(), /Copia guardada/);
    await page.locator('#favorites').click();
    assert.equal(await page.locator('.card').count(), 1);
    await page.locator('#all').click();
    await page.locator('#search').fill('Romaguera');
    assert.equal(await page.locator('.card').count(), 2);
    await page.locator('#search').fill('');
    if (evidence) await page.screenshot({path:path.join(ROOT, 'docs/images/03-offline.png'),fullPage:true});
    await page.setViewportSize({ width: 390, height: 844 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    if (evidence) await page.screenshot({path:path.join(ROOT, 'docs/images/04-movil.png'),fullPage:true});
    await context.setOffline(false);
    await page.waitForFunction(() => !document.querySelector('#refresh').disabled);
    const manifest = await (await context.request.get(new URL('manifest.json', BASE).href)).json();
    assert.equal(manifest.display, 'standalone');
    for (const icon of manifest.icons) assert.equal((await context.request.get(new URL(icon.src, BASE).href)).status(),200);
    const keys = await page.evaluate(() => caches.keys());
    assert(keys.includes('pocketstore-shell-v1'));
    assert.deepEqual(errors, []);
    // Primera visita con API caída: usar la copia incluida y luego recargar offline.
    const fallbackContext = await browser.newContext();
    await fallbackContext.route('https://jsonplaceholder.typicode.com/users', route => route.abort());
    const fallbackPage = await fallbackContext.newPage();
    await fallbackPage.goto(BASE);
    await fallbackPage.waitForFunction(() => document.querySelectorAll('.card').length === 10 && navigator.serviceWorker.controller && !document.querySelector('#refresh').disabled);
    assert.match(await fallbackPage.locator('#source').innerText(), /demostración/);
    await fallbackContext.setOffline(true);
    await fallbackPage.reload();
    await fallbackPage.waitForFunction(() => document.querySelectorAll('.card').length === 10);
    assert.equal(await fallbackPage.locator('#connection').innerText(), 'Sin conexión');
    await fallbackContext.close();
    await context.close();
    console.log('OK: catálogo, búsqueda, vacío, favoritos persistentes, ficha, Escape, recarga offline, reconexión, móvil, iconos y API caída.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
